from collections import defaultdict
from ranking_files.ranking import team_rankings, get_bonus

fcs_teams = {
    'North Dakota State', 'Sacramento State', 'Abilene Christian', 'Alabama A&M', 'Alabama State', 'Albany',
    'Alcorn State', 'Arkansas-Pine Bluff', 'Austin Peay', 'Bethune-Cookman', 'Bryant', 'Bucknell', 'Butler',
    'Cal Poly', 'Campbell', 'Central Arkansas', 'Central Connecticut', 'Charleston Southern',
}

fcs_aliases = {
    'ndsu': 'North Dakota State',
    'north dakota state': 'North Dakota State',
    'sac': 'Sacramento State',
    'sacramento state': 'Sacramento State',
    'abilene christian': 'Abilene Christian',
    'acu': 'Abilene Christian',
    'alabama a&m': 'Alabama A&M',
    'aamu': 'Alabama A&M',
    'alabama state': 'Alabama State',
    'alst': 'Alabama State',
    'ualbany': 'UAlbany',
    'alb': 'UAlbany',
    'alcorn state': 'Alcorn State',
    'alcn': 'Alcorn State',
    'arkansas-pine bluff': 'Arkansas-Pine Bluff',
    'uapb': 'Arkansas-Pine Bluff',
    'austin peay': 'Austin Peay',
    'apsu': 'Austin Peay',
    'bethune-cookman': 'Bethune-Cookman',
    'bcu': 'Bethune-Cookman',
    'bryant': 'Bryant',
    'bry': 'Bryant',
    'bucknell': 'Bucknell',
    'buck': 'Bucknell',
    'butler': 'Butler',
    'but': 'Butler',
    'cal poly': 'Cal Poly',
    'cp': 'Cal Poly',
    'campbell': 'Campbell',
    'cam': 'Campbell',
    'central arkansas': 'Central Arkansas',
    'cark': 'Central Arkansas',
    'central connecticut': 'Central Connecticut',
    'ccsu': 'Central Connecticut',
    'charleston southern': 'Charleston Southern',
    'chso': 'Charleston Southern',

}

# Add North Dakota State and Sacramento State after 2025 season
valid_fbs_teams = {
    "Boston College", "CAL", "Clemson", "Duke", "Florida State", "Georgia Tech", "Louisville", "Miami", "NC State",
    "UNC", "PITT", "SMU", "Stanford", "Syracuse", "Virginia", "Virginia Tech", "Wake Forest", "ARMY", "Charlotte",
    "East Carolina", "FAU", "Memphis", "NAVY", "North Texas", "RICE", "South Florida", "Temple", "Tulane", "Tulsa",
    "UAB", "UTSA", "Arizona State", "Arizona", "BYU", "Baylor", "Cincinnati", "Colorado", "Houston", "Iowa State",
    "Kansas", "Kansas State", "Oklahoma State", "TCU", "Texas Tech", "UCF", "UTAH", "West Virginia", "UL Monroe",
    "Indiana", "Ohio State", "USC", "Oregon", "Michigan", "Northwestern", "Nebraska", "Washington", "Iowa", "Minnesota",
    "UCLA", "Illinois", "Maryland", "Michigan State", "Penn State", "Rutgers", "Purdue", "Wisconsin", "Delaware",
    "FIU", "JAX STATE", "Kennesaw State", "Liberty", "Louisiana Tech", "Middle Tennessee", "Missouri State",
    "New Mexico State", "Sam Houston", "UTEP", "Western Kentucky", "Notre Dame", "UConn", "Akron", "Ball State",
    "Bowling Green", "Buffalo", "Central Michigan", "Eastern Michigan", "Kent State", "UMass", "M-OH",
    "Northern Illinois", "Ohio", "Toledo", "Western Michigan", "Air Force", "Boise State", "Colorado State",
    "Fresno State", "Hawai'i", "Nevada", "New Mexico", "San Diego State", "San Jose State", "UNLV", "Utah State",
    "Wyoming", "Oregon State", "Washington State", "Alabama", "Arkansas", "Auburn", "Florida", "Georgia", "Kentucky",
    "LSU", "Mississippi State", "Missouri", "Oklahoma", "Ole Miss", "South Carolina", "Tennessee", "Texas A&M", "Texas",
    "Vanderbilt", "App State", "Arkansas State", "Coastal Carolina", "Georgia Southern", "Georgia State",
    "James Madison", "Louisiana", "Marshall", "Old Dominion", "South Alabama", "Southern Miss", "Texas State", "TROY"
}

aliases = {
    "UL Monroe": "UL Monroe",
    "UL Monroe Warhawks": "UL Monroe",
    "ULM": "UL Monroe",
    "TROY": "TROY",
    "Troy Trojans": "TROY",
    "Texas State": "Texas State",
    "Texas State Bobcats": "Texas State",
    "TXST": "Texas State",
    "Southern Miss": "Southern Miss",
    "Southern Miss Golden Eagles": "Southern Miss",
    "USM": "Southern Miss",
    "South Alabama": "South Alabama",
    "South Alabama Jaguars": "South Alabama",
    "USA": "South Alabama",
    "Old Dominion": "Old Dominion",
    "Old Dominion Monarchs": "Old Dominion",
    "ODU": "Old Dominion",
    "Marshall": "Marshall",
    "Marshall Thundering Herd": "Marshall",
    "MRSH": "Marshall",
    "Louisiana": "Louisiana",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "UL": "Louisiana",
    "James Madison": "James Madison",
    "James Madison Dukes": "James Madison",
    "JMU": "James Madison",
    "Georgia State": "Georgia State",
    "Georgia State Panthers": "Georgia State",
    "GAST": "Georgia State",
    "Georgia Southern": "Georgia Southern",
    "Georgia Southern Eagles": "Georgia Southern",
    "GASO": "Georgia Southern",
    "Coastal Carolina": "Coastal Carolina",
    "Coastal Carolina Chanticleers": "Coastal Carolina",
    "CCU": "Coastal Carolina",
    "Arkansas State": "Arkansas State",
    "Arkansas State Red Wolves": "Arkansas State",
    "ARST": "Arkansas State",
    "App State": "App State",
    "App State Mountaineers": "App State",
    "APP": "App State",
    "Vanderbilt": "Vanderbilt",
    "Vanderbilt Commodores": "Vanderbilt",
    "VAN": "Vanderbilt",
    "Texas": "Texas",
    "Texas Longhorns": "Texas",
    "TEX": "Texas",
    "Texas A&M": "Texas A&M",
    "Texas A&M Aggies": "Texas A&M",
    "TA&M": "Texas A&M",
    "Tennessee": "Tennessee",
    "Tennessee Volunteers": "Tennessee",
    "TENN": "Tennessee",
    "South Carolina": "South Carolina",
    "South Carolina Gamecocks": "South Carolina",
    "SC": "South Carolina",
    "Ole Miss": "Ole Miss",
    "Ole Miss Rebels": "Ole Miss",
    "MISS": "Ole Miss",
    "Oklahoma": "Oklahoma",
    "Oklahoma Sooners": "Oklahoma",
    "OU": "Oklahoma",
    "Missouri": "Missouri",
    "Missouri Tigers": "Missouri",
    "MIZ": "Missouri",
    "Mississippi State": "Mississippi State",
    "Mississippi State Bulldogs": "Mississippi State",
    "MSST": "Mississippi State",
    "LSU": "LSU",
    "LSU Tigers": "LSU",
    "Kentucky": "Kentucky",
    "Kentucky Wildcats": "Kentucky",
    "UK": "Kentucky",
    "Georgia": "Georgia",
    "Georgia Bulldogs": "Georgia",
    "UGA": "Georgia",
    "Florida": "Florida",
    "Florida Gators": "Florida",
    "FLA": "Florida",
    "Auburn": "Auburn",
    "Auburn Tigers": "Auburn",
    "AUB": "Auburn",
    "Arkansas": "Arkansas",
    "Arkansas Razorbacks": "Arkansas",
    "ARK": "Arkansas",
    "Alabama": "Alabama",
    "Alabama Crimson Tide": "Alabama",
    "ALA": "Alabama",
    "Washington State": "Washington State",
    "Washington State Cougars": "Washington State",
    "WSU": "Washington State",
    "Oregon State": "Oregon State",
    "Oregon State Beavers": "Oregon State",
    "ORST": "Oregon State",
    "Wyoming": "Wyoming",
    "Wyoming Cowboys": "Wyoming",
    "WYO": "Wyoming",
    "USU": "Utah State",
    "Utah State": "Utah State",
    "Utah State Aggies": "Utah State",
    "UNLV": "UNLV",
    "UNLV Rebels": "UNLV",
    "San Jose State": "San Jose State",
    "San Jose State Spartans": "San Jose State",
    "SJSU": "San Jose State",
    "San Diego State": "San Diego State",
    "San Diego State Aztecs": "San Diego State",
    "SDSU": "San Diego State",
    "New Mexico": "New Mexico",
    "New Mexico Lobos": "New Mexico",
    "UNM": "New Mexico",
    "Nevada": "Nevada",
    "Nevada Wolf Pack": "Nevada",
    "NEV": "Nevada",
    "Hawai'i": "Hawai'i",
    "Hawai'i Rainbow Warriors": "Hawai'i",
    "HAW": "Hawai'i",
    "Fresno State": "Fresno State",
    "Fresno State Bulldogs": "Fresno State",
    "FRES": "Fresno State",
    "Colorado State": "Colorado State",
    "Colorado State Rams": "Colorado State",
    "CSU": "Colorado State",
    "Air Force": "Air Force",
    "Air Force Falcons": "Air Force",
    "AFA": "Air Force",
    "Western Michigan": "Western Michigan",
    "Western Michigan Broncos": "Western Michigan",
    "WMU": "Western Michigan",
    "Toledo": "Toledo",
    "Toledo Rockets": "Toledo",
    "TOL": "Toledo",
    "OHIO": "Ohio",
    "Ohio Bobcats": "Ohio",
    "Northern Illinois": "Northern Illinois",
    "Northern Illinois Huskies": "Northern Illinois",
    "NIU": "Northern Illinois",
    "Miami (OH) RedHawks": "M-OH",
    "Miami (OH)": "M-OH",
    "M-OH": "M-OH",
    "Massachusetts": "UMass",
    "UMass": "UMass",
    "Massachusetts Minuteman": "Massachusetts",
    "MASS": "UMass",
    "Kent State": "Kent State",
    "Kent State Golden Flashes": "Kent State",
    "KENT": "Kent State",
    "Eastern Michigan": "Eastern Michigan",
    "Eastern Michigan Eagles": "Eastern Michigan",
    "EMU": "Eastern Michigan",
    "Central Michigan": "Central Michigan",
    "Central Michigan Chippewas": "Central Michigan",
    "CMU": "Central Michigan",
    "Buffalo": "Buffalo",
    "Buffalo Bulls": "Buffalo",
    "BUFF": "Buffalo",
    "Bowling Green": "Bowling Green",
    "Bowling Green Falcons": "Bowling Green",
    "BGSU": "Bowling Green",
    "Ball State": "Ball State",
    "Ball State Cardinals": "Ball State",
    "BALL": "Ball State",
    "Akron": "Akron",
    "Akron Zips": "Akron",
    "AKR": "Akron",
    "UConn": "UConn",
    "UConn Huskies": "UConn",
    "CONN": "UConn",
    "Notre Dame": "Notre Dame",
    "Notre Dame Fighting Irish": "Notre Dame",
    "ND": "Notre Dame",
    "Western Kentucky": "Western Kentucky",
    "Western Kentucky Hilltoppers": "Western Kentucky",
    "WKU": "Western Kentucky",
    "UTEP": "UTEP",
    "UTEP Miners": "UTEP",
    "Sam Houston": "Sam Houston",
    "Sam Houston Bearkats": "Sam Houston",
    "SHSU": "Sam Houston",
    "New Mexico State": "New Mexico State",
    "New Mexico State Aggies": "New Mexico State",
    "NMSU": "New Mexico State",
    "Missouri State": "Missouri State",
    "Missouri State Bears": "Missouri State",
    "MOST": "Missouri State",
    "Middle Tennessee": "Middle Tennessee",
    "Middle Tennessee Blue Raiders": "Middle Tennessee",
    "MTSU": "Middle Tennessee",
    "Louisiana Tech": "Louisiana Tech",
    "Louisiana Tech Bulldogs": "Louisiana Tech",
    "LT": "Louisiana Tech",
    "Liberty": "Liberty",
    "Liberty Flames": "Liberty",
    "LIB": "Liberty",
    "Kennesaw State": "Kennesaw State",
    "Kennesaw State Owls": "Kennesaw State",
    "KENN": "Kennesaw State",
    "JAX STATE": "JAX STATE",
    "Jacksonville State": "JAX STATE",
    "Jacksonville State Gamecocks": "JAX STATE",
    "JVST": "JAX STATE",
    "FIU": "FIU",
    "Florida International": "FIU",
    "Florida International Panthers": "FIU",
    "Delaware": "Delaware",
    "Delaware Blue Hens": "Delaware",
    "DEL": "Delaware",
    "Wisconsin": "Wisconsin",
    "Wisconsin Badgers": "Wisconsin",
    "WIS": "Wisconsin",
    "Purdue": "Purdue",
    "Purdue Boilermakers": "Purdue",
    "PUR": "Purdue",
    "Rutgers": "Rutgers",
    "Rutgers Scarlet Knights": "Rutgers",
    "RUTG": "Rutgers",
    "PSU": "Penn State",
    "Penn State": "Penn State",
    "Penn State Nittany Lions": "Penn State",
    "MSU": "Michigan State",
    "MI State": "Michigan State",
    "Michigan State": "Michigan State",
    "Michigan State Spartans": "Michigan State",
    "MD": "Maryland",
    "Maryland": "Maryland",
    "Maryland Terrapins": "Maryland",
    "ILL": "Illinois",
    "Illinois": "Illinois",
    "Illinois Fighting Illini": "Illinois",
    "UCLA": "UCLA",
    "UCLA Bruins": "UCLA",
    "Minnesota": "Minnesota",
    "Minnesota Golden Gophers": "Minnesota",
    "MINN": "Minnesota",
    "IOWA": "Iowa",
    "Iowa Hawkeyes": "Iowa",
    "Washington": "Washington",
    "Washington Huskies": "Washington",
    "WASH": "Washington",
    "NEB": "Nebraska",
    "Nebraska": "Nebraska",
    "Nebraska Cornhuskers": "Nebraska",
    "NU": "Northwestern",
    "Northwestern": "Northwestern",
    "Northwestern Wildcats": "Northwestern",
    "MICH": "Michigan",
    "Michigan": "Michigan",
    "Michigan Wolverines": "Michigan",
    "Oregon": "Oregon",
    "Oregon Ducks": "Oregon",
    "ORE": "Oregon",
    "USC": "USC",
    "USC Trojans": "USC",
    "OSU": "Ohio State",
    "Ohio State": "Ohio State",
    "Ohio State Buckeyes": "Ohio State",
    "IU": "Indiana",
    "Indiana": "Indiana",
    "Indiana Hoosiers": "Indiana",
    "West Virginia": "West Virginia",
    "West Virginia Mountaineers": "West Virginia",
    "WVU": "West Virginia",
    "UTAH": "UTAH",
    "Utah": "UTAH",
    "Utah Utes": "UTAH",
    "UCF": "UCF",
    "UCF Knights": "UCF",
    "Texas Tech": "Texas Tech",
    "Texas Tech Red Raiders": "Texas Tech",
    "TTU": "Texas Tech",
    "TCU": "TCU",
    "TCU Horned Frogs": "TCU",
    "Oklahoma St.": "Oklahoma State",
    "Oklahoma State": "Oklahoma State",
    "Oklahoma State Cowboys": "Oklahoma State",
    "OKST": "Oklahoma State",
    "Kansas St.": "Kansas State",
    "Kansas State": "Kansas State",
    "Kansas State Wildcats": "Kansas State",
    "KSU": "Kansas State",
    "Kansas": "Kansas",
    "Kansas Jayhawks": "Kansas",
    "KU": "Kansas",
    "Iowa St.": "Iowa State",
    "Iowa State": "Iowa State",
    "Iowa State Cyclones": "Iowa State",
    "ISU": "Iowa State",
    "Houston": "Houston",
    "Houston Cougars": "Houston",
    "HOU": "Houston",
    "Colorado": "Colorado",
    "Colorado Buffaloes": "Colorado",
    "COLO": "Colorado",
    "Cincinnati": "Cincinnati",
    "Cincinnati Bearcats": "Cincinnati",
    "CIN": "Cincinnati",
    "Baylor": "Baylor",
    "Baylor Bears": "Baylor",
    "BAY": "Baylor",
    "BYU": "BYU",
    "BYU Cougars": "BYU",
    "Arizona": "Arizona",
    "Arizona Wildcats": "Arizona",
    "ARIZ": "Arizona",
    "Arizona St.": "Arizona State",
    "Arizona State": "Arizona State",
    "Arizona State Sun Devils": "Arizona State",
    "ASU": "Arizona State",
    "UTSA": "UTSA",
    "UTSA Roadrunners": "UTSA",
    "UAB": "UAB",
    "UAB Blazers": "UAB",
    "Tulane": "Tulane",
    "Tulane Green Wave": "Tulane",
    "TULN": "Tulane",
    "Tulsa": "Tulsa",
    "Tulsa Golden Hurricane": "Tulsa",
    "TLSA": "Tulsa",
    "Temple": "Temple",
    "Temple Owls": "Temple",
    "TEM": "Temple",
    "South Florida": "South Florida",
    "South Florida Bulls": "South Florida",
    "USF": "South Florida",
    "Rice": "RICE",
    "Rice Owls": "RICE",
    "RICE": "RICE",
    "North Texas": "North Texas",
    "North Texas Mean Green": "North Texas",
    "UNT": "North Texas",
    "NAVY": "NAVY",
    "Navy": "NAVY",
    "Navy Midshipmen": "NAVY",
    "Memphis": "Memphis",
    "Memphis Tigers": "Memphis",
    "MEM": "Memphis",
    "FAU": "FAU",
    "Florida Atlantic": "FAU",
    "Florida Atlantic Owls": "FAU",
    "East Carolina": "East Carolina",
    "East Carolina Pirates": "East Carolina",
    "ECU": "East Carolina",
    "Charlotte": "Charlotte",
    "Charlotte 49ers": "Charlotte",
    "CLT": "Charlotte",
    "Army": "ARMY",
    "ARMY": "ARMY",
    "Army Black Knights": "ARMY",
    "Wake Forest": "Wake Forest",
    "Wake Forest Demon Deacons": "Wake Forest",
    "WAKE": "Wake Forest",
    "Virginia Tech": "Virginia Tech",
    "Virginia Tech Hokies": "Virginia Tech",
    "VT": "Virginia Tech",
    "Virginia": "Virginia",
    "Virginia Cavaliers": "Virginia",
    "UVA": "Virginia",
    "Syracuse": "Syracuse",
    "Syracuse Orange": "Syracuse",
    "SYR": "Syracuse",
    "Stanford": "Stanford",
    "Stanford Cardinal": "Stanford",
    "STAN": "Stanford",
    "SMU": "SMU",
    "SMU Mustangs": "SMU Mustangs",
    "Pittsburgh": "PITT",
    "Pittsburgh Panthers": "PITT",
    "PITT": "PITT",
    "North Carolina": "UNC",
    "North Carolina Tar Heels": "UNC",
    "UNC": "UNC",
    "Boise State Broncos": "Boise State",
    "Boise State": "Boise State",
    "BOIS": "Boise State",
    "Boston College": "Boston College",
    "Boston College Eagles": "Boston College",
    "BC": "Boston College",
    "CAL": "CAL",
    "California": "CAL",
    "California Golden Bears": "CAL",
    "Clemson": "Clemson",
    "Clemson Tigers": "Clemson",
    "CLEM": "Clemson",
    "Duke": "Duke",
    "Duke Blue Devils": "Duke",
    "DUKE": "Duke",
    "Florida St.": "Florida State",
    "Florida State": "Florida State",
    "Florida State Seminoles": "Florida State",
    "FSU": "Florida State",
    "Georgia Tech": "Georgia Tech",
    "Georgia Tech Yellow Jackets": "Georgia Tech",
    "GT": "Georgia Tech",
    "Louisville": "Louisville",
    "Louisville Cardinals": "Louisville",
    "LOU": "Louisville",
    "Miami": "Miami",
    "Miami Hurricanes": "Miami",
    "MIA": "Miami",
    "NC State": "NC State",
    "NC State Wolfpack": "NC State",
    "NCSU": "NC State"
}

fbs_aliases = {k.lower(): v for k, v in aliases.items()}


def normalize_team(name):
    """Convert a team name to its canonical form using aliases."""
    return fbs_aliases.get(name.lower())


def rank_fbs_from_games(games, max_iterations=1000, tolerance=1e-3):
    """
    Rank Division 1 FBS College Football teams based on game results and opponent strength.

    games: list of tuples (team1, team2, team1_points, team2_points, week [, overtime])
      - team1_points > team2_points → team1 wins
      - team2_points > team1_points → team2 wins
      - valueError is raised if there is a tie
      - optional 5th value (bool): True = game went to overtime
      - if either team1 or team2 is not in the Division 1 FBS
        * the team not in the FBS does not get a power score
        * the valid team will get minimum value from a win (3 pts) and maximum value from a loss (-20 pts)
    """
    # Normalize and extract teams
    normalized = []
    for game in games:
        if len(game) == 6:
            team1, team2, pts1, pts2, week, overtime = game
        else:
            team1, team2, pts1, pts2, week = game
            overtime = False

        t1 = normalize_team(team1)
        t2 = normalize_team(team2)

        if pts1 == pts2:
            raise ValueError(f"Ties are not allowed in college rankings: {team1} vs {team2}, {week}")

        diff = abs(pts1 - pts2)
        if overtime:
            bonus = -2
        else:
            # bonus = 0 if either team is not in valid_fbs_teams
            bonus = get_bonus(diff, 'FBS') if (t1 in valid_fbs_teams and t2 in valid_fbs_teams) else 0

        result = 0 if pts1 > pts2 else 1
        normalized.append((t1, t2, result, bonus))

    start_score = 100.0
    teams = {t for g in normalized for t in g[:2] if t in valid_fbs_teams}
    scores = {team: start_score for team in teams}
    record = defaultdict(lambda: {"wins": 0, "losses": 0})

    # Track record
    for team1, team2, result, _ in normalized:
        if result == 0:
            if team1 in valid_fbs_teams:
                record[team1]["wins"] += 1
            if team2 in valid_fbs_teams:
                record[team2]["losses"] += 1
        elif result == 1:
            if team2 in valid_fbs_teams:
                record[team2]["wins"] += 1
            if team1 in valid_fbs_teams:
                record[team1]["losses"] += 1

    # Iterative scoring
    for _ in range(max_iterations):
        new_scores = team_rankings(teams, normalized, scores, 3.0, 5.0, 'FBS')

        diffs = [abs(new_scores[t] - scores[t]) for t in scores]
        scores = new_scores
        if all(d < tolerance for d in diffs):
            break

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    results = [
        (team, score, record[team]["wins"], record[team]["losses"])
        for team, score in ranked
    ]
    return results
